//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLearning.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSubject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserSubject()
        {
            this.UserModul = new HashSet<UserModul>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDBenutzer { get; set; }
        public string Name { get; set; }
    
        public virtual Benutzer Benutzer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserModul> UserModul { get; set; }
    }
}
